### ISSUE TITLE
Add support for Bouquet Projects

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/planet-donations#120]
Fetch the Payment Options
Step 1: Use bouquet purpose to determine whether a bouquet is for tree or for conservation.
Step 2. Populate the form with the options.

Payment flow doesn't change.

- [x] Add UI
- [x] Add Response

**Comment by jmiridis** [comment]
### Endpoints for bouquet projects
- get purpose
`https://app-staging.plant-for-the-planet.org/app/projects/proj_L3SE2oNK202WMpxSfLnWpY6T`

- get payment config
`https://app-staging.plant-for-the-planet.org/app/projects/proj_L3SE2oNK202WMpxSfLnWpY6T/paymentOptions`

Another project without free amount: `proj_L0rlap9qIj9FVU1hrrkzG4iv`
