### ISSUE TITLE
Bouquet donations having wrong tenant_id leading to error downloading certificate

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/planet-donations#147]
**Describe the bug**
From time to time we get some bouquet donations (which we currently only offer for our TfJ tenant), but which got the default tenant_id=1 in our database. So maybe we somehow miss to send the right tenant to the backend?

A side effect of this is that the users cannot download the certificate for this donation.

**Is it on a Production or Development Build?**
production

**Comment by mariahosfeld** [comment]
Seems to be outdated, therefore closing it.
