### ISSUE TITLE
Fix layout for displaying large donation amounts for Bouquet projects

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/planet-donations#152]
**Describe the bug**
Large donation amounts do not fit in the layout for Bouquet projects, e.g. for Mexican currency MXN on Treesforjane.org at https://donate.plant-for-the-planet.org/?tenant=ten_1e5WejOp&to=proj_xkTKfkV2uKk9COvugnCpGl6c

**Is it on a Production or Development Build?**
production

**To Reproduce**
1. Go to https://donate.plant-for-the-planet.org/?tenant=ten_1e5WejOp&to=proj_xkTKfkV2uKk9COvugnCpGl6c
2. Choose currency MXN
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/1532418/141648660-7ff17aec-1965-4b5f-8706-cd0f1a93635d.png)

**Desktop (please complete the following information):**
- OS: latest MacOS
- Browser: latest Chrome

**Comment by sagararyal** [comment]
I recommend removing currency from non custom amounts. 
![Screen Shot 2021-11-15 at 3 33 50 PM](https://user-images.githubusercontent.com/5401575/141799658-bbebc043-e386-4555-9cc2-893337ff631d.png)
