### ISSUE TITLE
Allow Donation payments with PlanetCash

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/planet-donations#235]
**Describe the feature you'd like to see included in Planet Pay.**
When implemented this feature will allow logged-in users to donate with PlanetCash, if they have a PlanetCash Account.

PlanetCash Payments should not have a minimum amount.

**What are the use cases for this feature?**
User should not be required to enter donation details. Billing details from the profile should be used for donation, unless, the donation is `OnBehalf` Donation.

(Donate with PlanetCash) Button on top of Donate with Apple/Google Pay on the main page.

PlanetCash Account can be checked by reviewing the /profile endpoint.

PlanetCash Donations can be made by using the user's OAuth token.

```
{
    "project": "proj_Th9LgTUT7wolxBRMY",
    "purpose": "conservation",
    "prePaid": true, (Must be 
    "units": 10,
    "amount": 15, (optional if units is passed) pass either units or amount)
    "currency": "EUR",
    "donor": {    //donor object is only necessary if a donation has onBehlaf = true
        "firstname": "ea in officia",
        "lastname": "officia voluptate ipsum",
        "email": "deserunt laborum sint",
        "address": "nostru",
        "city": "id veniam",
        "zipCode": "Duis pariatur minim ea",
        "country": "fugiat culpa",
        "companyname": "sit eiusmod fugiat",
        "tin": "s",
        "notify": true
    },
    "gift": { // only if the PlanetCash donation contains gift
        "type": "invitation",
        "recipientProfile": "prf_WH6OY9ZKpesIM7Gx4Q",
        "recipientEmail": "Ut dolore ut aute cillum",
        "recipientName": "irure nostrud qui Lorem",
        "message": "Excepteur consectetur",
        "occassion": "sit et",
        "notify": true
    },
    "onBehalf": true
}
```

Donations with PlanetCash are not tax-deductible.

**Feature Checklist**

- [x] I have searched for existing issues and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request requires change in APIs, Backend, etc

**Comment by sagararyal** [comment]
- [ ] Show available PlanetCash balance, if account exists.

<img width="394" alt="Screen Shot 2022-02-17 at 1 24 36 PM" src="https://user-images.githubusercontent.com/5401575/154481316-1bc6e067-c4b7-4370-bb37-65d6d721dfc6.png">

Comonent: PlanetCash Selector

The component is visible if the user is logged in, and user has planetCash account.

Context values for PlanetCash Selector

- Available PlanetCash balance
- User Selected Amount
- TreeCash Account Guid (for TopUp)

Default Behavior:
If amount =< planetCash  Balance -> Activate
If amount > planetCash Balance --> deactivate Donate with PlanetCash

generate topup link: donate.plant-for-the-planet.org/?to=tca_acct-guid

When user changes amount of donation,  as long as the above rules satisfy,  activate/deactivate the button.


If PlanetCash is not active, the current flow is unchanged.

However, When PlanetCash is active for Donation:

- [ ] Remove  `tax deduction component` as PlanetCash donations cannot be tax deductible.

- [ ] Add an option "This donation is on behalf of someone"

- [ ] Remove Native Pay/ Continue with PayPal buttons.

<img width="386" alt="Screen Shot 2022-02-17 at 1 39 01 PM" src="https://user-images.githubusercontent.com/5401575/154483548-20643c82-818a-4d9a-b0dd-2ca9abefd8d2.png">


<img width="428" alt="Screen Shot 2022-02-17 at 1 39 28 PM" src="https://user-images.githubusercontent.com/5401575/154483620-f1fd897e-ceaa-4853-bd6e-7169fb964d64.png">

**Comment by jmiridis** [comment]
Fetching TreeCash information using an authenticated request:

`GET https://app-staging.plant-for-the-planet.org/app/treeCash/tca_tbT7Zmvhft6nEKAVh4RppY6H`

```
{
    "id": "tca_tbT7Zmvhft6nEKAVh4RppY6H",
    "ownerName": "Matthias Betz",
    "balance": -300,
    "debit": 300,
    "creditLimit": 600,
    "currency": "EUR",
    "country": "DE",
    "topUpThreshold": null,
    "topUpAmount": null,
    "isActive": true,
    "fee": 0
}
```

**Comment by jmiridis** [comment]
Fetching PlanetCash information from the authenticated users profile (see property `planetCash` below):

`GET  https://app.plant-for-the-planet.org/app/profile`

```
{
    "id": "prf_h6smcMDN23Qet1CP7BEplM60",
    "slug": "sagar-aryal",
    "type": "individual",
    "currency": "EUR",
    "name": null,
    "firstname": "Sagar",
    "lastname": "Aryal",
    "country": "DE",
    "email": "[sagar.aryal@plant-for-the-planet.org](mailto:sagar.aryal@plant-for-the-planet.org)",
    "image": "5e5314f0abfed825020754.jpeg",
    "url": "https://www.linkedin.com/in/sagararyal/",
    "urlText": "LinkedIn",
    "planetCash": {
        "account": "pcash_nrug7zPLxJP6974FVWm7z6TS",
        "balance": 0,
        "creditLimit": 0
    },
    "displayName": "Sagar Aryal",
    "score": {
        "personal": 100.0,
        "received": 14.8,
        "target": 1000.0
    },
    "supportedProfile": "prf_P0BbQ7CQMjrbDjjYQos232Np",
    "isReviewer": true,
    "isPrivate": false,
    "getNews": false,
    "bio": "I have been planting trees and encouraging people to take action against climate crisis ever since I was 10 years old. This app is one of many solution for those of us who want to do something but don't have easy tools to contribute.  Please join me and 100k+ users to plant more trees.",
    "address": {
        "address": "Metastraße 21",
        "city": "Berlin",
        "zipCode": "10317",
        "country": "DE"
    },
    "locale": "en",
    "hasLogoLicense": true,
    "tin": null
}
```
